import Head from 'next/head';
import Image from 'next/image';
import EventOne from "../components/Events/EventOne/EventOne";
import EventTwo from "../components/Events/EventTwo/EventTwo";
import Footer from "../components/Footer/Footer";
import Hero from "../components/Hero/Hero";
import Navigation from "../components/Navigation/Navigation";
import Services from "../components/Services/Services";
import Slogan from "../components/Slogan/Slogan";
import Testimonials from "../components/Testimonials/Testimonials";
import UiOne from "../Ui/UiOne";
import UiTwo from "../Ui/UiTwo";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="relative">
        <UiTwo />
        <UiOne />
        <Navigation />
        <div className="px-5  ">
          <Hero />
          <Slogan />
          <Services />
          <EventOne />
          <EventTwo />
          <Testimonials />
        </div>
        <Footer />

      </main>


    </div>
  )
}
